"""security_limits 모듈의 공개 동작을 설명합니다.

Args:
    없음

Returns:
    None: 처리 결과를 반환합니다.
"""
from __future__ import annotations

MIB = 1024 * 1024

MAX_SOURCE_TEXT_BYTES = 2 * MIB
MAX_SOURCE_UPLOAD_BYTES = 4 * MIB
MAX_PACK_UPLOAD_BYTES = 200 * MIB
MAX_REMOTE_DOWNLOAD_BYTES = 200 * MIB
MAX_ARCHIVE_TOTAL_BYTES = 200 * MIB
MAX_ARCHIVE_FILE_BYTES = 50 * MIB
MAX_ARCHIVE_MEMBERS = 5000

__all__ = [
    "MAX_ARCHIVE_FILE_BYTES",
    "MAX_ARCHIVE_MEMBERS",
    "MAX_ARCHIVE_TOTAL_BYTES",
    "MAX_PACK_UPLOAD_BYTES",
    "MAX_REMOTE_DOWNLOAD_BYTES",
    "MAX_SOURCE_TEXT_BYTES",
    "MAX_SOURCE_UPLOAD_BYTES",
    "MIB",
]
