from __future__ import annotations

MIB = 1024 * 1024

MAX_SOURCE_TEXT_BYTES = 2 * MIB
MAX_SOURCE_UPLOAD_BYTES = 4 * MIB
MAX_STUDIO_UPLOAD_FILES = 32
MAX_STRESS_SOLUTIONS = 128
MAX_STRESS_CASES = 10_000
MAX_STRESS_GENERATED_INPUT_BYTES = 4 * MIB
MAX_STRESS_GENERATOR_ARGS = 64
MAX_STRESS_ARGUMENT_BYTES = 4096
MAX_PACK_UPLOAD_BYTES = 200 * MIB
MAX_REMOTE_DOWNLOAD_BYTES = 200 * MIB
MAX_ARCHIVE_TOTAL_BYTES = 200 * MIB
MAX_ARCHIVE_FILE_BYTES = 50 * MIB
MAX_ARCHIVE_MEMBERS = 5000

__all__ = [
    "MAX_ARCHIVE_FILE_BYTES",
    "MAX_ARCHIVE_MEMBERS",
    "MAX_ARCHIVE_TOTAL_BYTES",
    "MAX_PACK_UPLOAD_BYTES",
    "MAX_REMOTE_DOWNLOAD_BYTES",
    "MAX_SOURCE_TEXT_BYTES",
    "MAX_SOURCE_UPLOAD_BYTES",
    "MAX_STUDIO_UPLOAD_FILES",
    "MAX_STRESS_ARGUMENT_BYTES",
    "MAX_STRESS_CASES",
    "MAX_STRESS_GENERATED_INPUT_BYTES",
    "MAX_STRESS_GENERATOR_ARGS",
    "MAX_STRESS_SOLUTIONS",
    "MIB",
]
